name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
          - name: echo a String
            run: echo "Hello World"
          - name: Multiline Commands
            run: |
              node -v
              npm -v
    parallel-jon-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: se_vers
    dependant-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a String
              run: Write-Output "Windows String"
            - name: Error Step
              run: doesnotexists